const SKILLS = [
  {
    id: 1,
    title: "Front-End Development",
    description: "Building engaging and user-friendly web interfaces using modern frameworks and technologies with expertise.",
    devicons: ["devicon-react-original colored", "devicon-vitejs-plain colored", "devicon-html5-plain colored", "devicon-css3-plain colored", "devicon-javascript-plain colored", "devicon-tailwindcss-plain colored"],
    tags: ["React.js", "Vite", "HTML5", "CSS3", "JavaScript", "Tailwind CSS"],
    size: "normal",
  },
  {
    id: 2,
    title: "Styling & Design",
    description: "Crafting visually appealing and responsive designs with advanced styling tools and frameworks.",
    devicons: ["devicon-css3-plain colored", "devicon-tailwindcss-plain colored", "devicon-bootstrap-plain colored", "devicon-figma-plain colored", "devicon-sass-plain colored"],
    tags: ["CSS3", "Tailwind CSS", "Bootstrap", "Figma", "Sass"],
    size: "normal",
  },
  {
    id: 3,
    title: "Programming Languages",
    description: "Proficient in problem-solving and applying programming languages to implement efficient data structures and algorithms.",
    devicons: ["devicon-java-plain colored", "devicon-python-plain colored", "devicon-javascript-plain colored", "devicon-typescript-plain colored"],
    tags: ["Java", "Python", "JavaScript", "TypeScript"],
    size: "small",
  },
  {
    id: 4,
    title: "Back-End Development",
    description: "Developing robust server-side logic and APIs to power dynamic and scalable web applications.",
    devicons: ["devicon-java-plain colored", "devicon-spring-plain colored", "devicon-hibernate-plain colored", "devicon-maven-plain colored"],
    tags: ["Java", "Spring Boot", "Spring Security", "Spring AI", "JWT", "REST APIs", "JPA", "Hibernate", "MVC"],
    size: "normal",
  },
  {
    id: 5,
    title: "Web Animations",
    description: "Creating seamless animations and transitions to enhance user engagement and interactivity.",
    devicons: ["devicon-javascript-plain colored", "devicon-css3-plain colored", "devicon-react-original colored"],
    tags: ["GSAP", "CSS Animations", "Framer Motion", "Transitions"],
    size: "normal",
  },
  {
    id: 6,
    title: "Database Management",
    description: "Designing and managing databases to ensure secure and efficient data storage and retrieval.",
    devicons: ["devicon-postgresql-plain colored", "devicon-mysql-plain colored", "devicon-firebase-plain colored", "devicon-mongodb-plain colored"],
    tags: ["PostgreSQL", "MySQL", "Firebase", "MongoDB", "H2", "JPA", "Query Optimization"],
    size: "small",
  },
  {
    id: 7,
    title: "Core Computer Science",
    description: "Strong foundation in core CS disciplines including problem-solving, system design, and efficient computing techniques.",
    devicons: [],
    tags: ["Operating Systems", "Computer Networks", "OOP", "DSA", "System Design", "UML", "SOLID Principles", "Design Patterns"],
    size: "tag-only",
  },
  {
    id: 8,
    title: "Mobile App Development",
    description: "Creating mobile apps with sleek designs and robust functionality.",
    devicons: ["devicon-androidstudio-plain colored", "devicon-react-original colored", "devicon-firebase-plain colored"],
    tags: ["Android Studio", "React Native", "Firebase"],
    size: "small",
  },
  {
    id: 9,
    title: "Version Control & Collaboration",
    description: "Effectively managing code and collaborating on projects to ensure seamless teamwork.",
    devicons: ["devicon-git-plain colored", "devicon-github-original", "devicon-maven-plain colored", "devicon-gradle-plain colored"],
    tags: ["Git", "GitHub", "Maven", "Gradle"],
    size: "small",
  },
  {
    id: 10,
    title: "Cloud & Deployment",
    description: "Experienced in deploying and managing applications using modern cloud platforms and tools.",
    devicons: ["devicon-amazonwebservices-plain-wordmark colored", "devicon-firebase-plain colored", "devicon-vercel-original", "devicon-docker-plain colored"],
    tags: ["AWS", "Firebase", "Vercel", "Docker basics", "CI/CD"],
    size: "normal",
  },
  {
    id: 11,
    title: "Testing & Debugging",
    description: "Ensuring code quality and reliability through rigorous testing and debugging processes.",
    devicons: ["devicon-junit-plain colored", "devicon-postman-plain colored", "devicon-swagger-plain colored"],
    tags: ["JUnit", "Postman", "Swagger UI", "API Testing", "Unit Testing"],
    size: "normal",
  },
  {
    id: 12,
    title: "UI/UX Design",
    description: "Designing user-centric interfaces that are intuitive, visually appealing, and easy to navigate.",
    devicons: ["devicon-figma-plain colored"],
    tags: ["Figma", "Prototyping", "Wireframing", "User Research", "Design Systems"],
    size: "tag-only",
  },
  {
    id: 13,
    title: "AI / ML",
    description: "Exploring machine learning concepts and applying AI tools to real-world projects.",
    devicons: ["devicon-python-plain colored", "devicon-scikitlearn-plain colored", "devicon-tensorflow-original colored", "devicon-jupyter-plain colored"],
    tags: ["Python", "Scikit-learn", "Neural Networks", "Soft Computing", "Spring AI"],
    size: "normal",
  },
  {
    id: 14,
    title: "Personal Development",
    description: "Committed to continuous learning and growth in both professional and collaborative environments.",
    devicons: [],
    tags: ["Time Management", "Problem Solving", "Communication", "Leadership", "Teamwork", "Adaptability"],
    size: "tag-only",
  },
];

export default SKILLS;